version: "3.4"

volumes:
  astro_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - qa-api
      - qa-ui
    ports:
      - 7800:7800

  qa-api:
    build:
      context: qa-api
      dockerfile: Dockerfile.prod
    image: qa-api
    restart: "on-failure"
    expose:
      - 7777
    depends_on:
      - database
      - flyway
    env_file:
      - projectprod.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  qa-ui:
    build: qa-ui
    image: qa-ui
    restart: "on-failure"
    expose:
      - 3000:80
    depends_on:
      - qa-api
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  llm-api:
    build: llm-api
    image: llm-api
    restart: "no"
    expose:
      - 7000

  database:
    container_name: database-server-edulearn-prod
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - ./production-database-data:/var/lib/postgresql/data
    env_file:
      - projectprod.env

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - projectprod.env

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - projectprod.env
    depends_on:
      - database

  playwright:
    entrypoint: "/bin/true"
    build: playwright
    network_mode: host
    depends_on:
      - nginx
    volumes:
      - ./playwright/tests:/app/tests
