apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    worker_processes 1;

    events {
      worker_connections 1024;
    }

    http {
      upstream qa-api {
        server qa-api-service:7777;
      }

      upstream qa-ui {
        server qa-ui-service:3000;
      }

      upstream llm-api {
        server llm-api-service:7000;
      }

      server {
        listen 7800;

        location /api/qa/ {
          proxy_pass http://qa-api/;
        }

        location /api/llm {
          proxy_pass http://llm-api/;
        }

        location / {
          proxy_pass http://qa-ui;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $host;
        }
      }
    }
