FROM lukechannings/deno:v1.37.0

EXPOSE 7777

WORKDIR /app

COPY deps.js .

RUN deno cache deps.js

COPY . .

RUN rm /app/database/database.js
RUN mv /app/database/database_kube.js /app/database/database.js

CMD [ "run", "--unstable", "--watch", "--allow-net", "--allow-read", "--allow-env", "app.js" ]COPY database/database2.js /app/database/database2.js